name: christine_s_application20
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  http: ^1.2.0
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_svg_provider: ^1.0.7
  dotted_border: ^2.1.0
  intl: ^0.18.0
  dio: ^5.4.0
  iconsax: ^0.0.8
  get: ^4.6.6
  shared_preferences: ^2.0.15
  jwt_decoder:
  another_stepper: ^1.2.2
  image_picker: ^1.0.7
  socket_io_client: ^3.0.0-beta.2
  provider: ^6.0.0
  json_annotation: ^4.0.1
  flutter_dotenv: ^5.0.2
dev_dependencies: 
  build_runner: ^2.0.6
  json_serializable: ^6.1.4
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
